# Generated by Django 2.2.4 on 2024-05-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20240518_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
