# Generated by Django 2.2.4 on 2024-05-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20240518_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
